apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: cluster-autoscaler
spec:
  manual: true
  versionStreamFormat: ${{cluster-autoscaler}}-${{versions.major}}
status:
  latestVersion: 1.29.0
  versions:
    - releaseDate: "2023-12-27"
      version: "1.29"    
    - releaseDate: "2023-08-28"
      version: "1.28"  
    - releaseDate: "2023-08-08"
      version: "1.27"
    - releaseDate: "2023-02-01"
      version: "1.26"
